add zarinpal payment system
sadeghesfahani/e-commerce pull request #12
Opened 2022-09-04 20:12 UTC by MrN-19

Hello Mr Sina , This i add a payment feature to project , hope to accept

2022-09-05 02:52 UTC, sadeghesfahani commented
سلام، ممنونم از مشارکت شما. چند مورد برای مرج شدن نیاز هست:
۱- در بخش وریفای، چطور ما به اون ترنزکشن انجام شده رفرنس میدیم؟ من متوجه این بخش نشدم. 
۲- اگر محبت کنید داکیومنتیشنی از زرین پال هم به اشتراک بذارید ممنون میشم.

2022-09-05 10:16 UTC, MrN-19 commented
درود بر شما , توضیح کلی به این صورت هست که ما یک متد pay داریم که عملیات پرداخت رو انجام میده و یک متد دیگه داریم که میاد بعد از 
پرداخت بررسی میکنه که عملیات به درستی انجام شده یا نه که اون متد verify هست , من باید کد های پروژه رو دوباره بخونم تا مسلط شم که بتونم کلاسی که نوشته شده رو به درخواست ها متصل کنم , فعلا عملیات اصلی رو نوشتم و یک دیگه کار داره , امیدوارم مفید بوده باشد

در ضمن اسناد مربوط به زرین پال رو خدمتتون ارسال میکنم

2022-09-05 10:22 UTC, sadeghesfahani commented
عموما در پرداخت ها برای وریفای یا از webhook استفاده میشه یا در صورتی که نیاز به وریفای باشه باید یک رفرنس به سمت سرور فرستاده بشه تا سرور مبدا بدونه چه ترنزکشنی رو باید وریفای کنه یا نکنه. با تشکر از شما

2022-09-05 11:05 UTC, MrN-19 commented
پس این تغییر انجام شده کاربردی نیست درسته ؟

2022-09-05 12:38 UTC, sadeghesfahani commented
از اونجایی که ویو برای تست وجود نداره و داکیومنتیشنو ندیدم نمیدونم.

2022-09-06 03:42 UTC, sadeghesfahani requested changes
با تشکر از مشارکت شما، با توجه به اینکه ویو و یو آر ال برای تست وجود ندارد و به نظر میرسه ورودی های بخش وریفای تابع کافی نیست. این پول رکوئست رو درخواست تغییر میزنم.

2022-09-06 03:43 UTC, closed without merging